# Grafana 数据源配置
#
# 自动配置 Prometheus 和 Loki 数据源
#

apiVersion: 1

datasources:
  # Prometheus 数据源
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  # Loki 数据源 (日志)
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false

  # PostgreSQL 数据源
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: openclaw_prod
    user: openclaw_admin
    secureJsonData:
      password: Oc@2026!Pg#Secure
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
    editable: false
